[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-core>=1.11.3",
    "dbt-snowflake>=1.11.1",
    "snowflake-connector-python>=4.2.0",
]
